name: allyn_scaffolding_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  animated_flip_counter: ^0.2.1
  collection: ^1.16.0
  connectivity_plus: ^4.0.0
  cookie_jar: ^4.0.2
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.4
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.5
  flutter_slidable: ^3.0.0
  flutter_smart_dialog: ^4.8.2+4
  flutter_svg: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  html: ^0.15.0
  html_unescape: ^2.0.0
  intl: ^0.18.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  json_annotation: ^4.8.0
  logging: ^1.0.2
  nil: ^1.1.1
  package_info_plus: ^4.0.0
  palette_generator: ^0.3.3
  path_provider: ^2.0.8
  riverpod_annotation: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.0
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.2.3

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^2.0.1
  intl_utils: ^2.8.1
  isar_generator: ^3.1.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.0
  riverpod_lint: ^1.3.0


flutter:
  uses-material-design: true

  assets:

    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/images/

  # assets end
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/icon_font.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated